<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8341" started-at="2016-03-03T09:38:51Z" finished-at="2016-03-03T09:38:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8341" started-at="2016-03-03T09:38:51Z" finished-at="2016-03-03T09:38:59Z">
      <class name="com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest">
        <test-method status="PASS" signature="getBrowser()[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="getBrowser" is-config="true" duration-ms="6187" started-at="2016-03-03T16:38:44Z" finished-at="2016-03-03T16:38:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getBrowser -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="setup" is-config="true" duration-ms="3476" started-at="2016-03-03T16:38:51Z" finished-at="2016-03-03T16:38:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="checkRegInvalid(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="checkRegInvalid" duration-ms="260" started-at="2016-03-03T16:38:54Z" data-provider="register" finished-at="2016-03-03T16:38:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Quyen]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ta]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0987654321']]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test@mail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123 Lincold Street]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[NewYork]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[New Jersey]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[700123]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[United States]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[quyentx]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[password1']]>
              </value>
            </param>
            <param index="11">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://newtours.demoaut.com/mercuryregister.php] but found [about:blank]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://newtours.demoaut.com/mercuryregister.php] but found [about:blank]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest.checkRegInvalid(RegTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkRegInvalid -->
        <test-method status="FAIL" signature="checkRegisterValid()[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="checkRegisterValid" duration-ms="4157" started-at="2016-03-03T16:38:55Z" finished-at="2016-03-03T16:38:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://newtours.demoaut.com/mercuryregister.php] but found [http://newtours.demoaut.com/create_account_success.php?osCsid=c36e62b8b56727e8cb5c785b60b7024e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://newtours.demoaut.com/mercuryregister.php] but found [http://newtours.demoaut.com/create_account_success.php?osCsid=c36e62b8b56727e8cb5c785b60b7024e]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.vsii.tsc.TSCSelenium05.quyentx.POM.RegPOM.checkRegister(RegPOM.java:84)
	at com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest.checkRegisterValid(RegTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkRegisterValid -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-03-03T16:38:59Z" finished-at="2016-03-03T16:38:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest@d072a9]" name="afterClass" is-config="true" duration-ms="21" started-at="2016-03-03T16:38:59Z" finished-at="2016-03-03T16:38:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.vsii.tsc.TSCSelenium05.quyentx.Test.RegTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
